# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/checkpoint/
Content-Type: application/json

{
  "name": "test",
  "position": {
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  "velocity": [
  ]
}
